#ifndef _ERROR_HANDLING_H_
#define _ERROR_HANDLING_H_


typedef enum{
	IO_EXPANDER_INIT_FAIL,
	ADS1293_INIT_FAIL,
	MAX86150_INIT_FAIL,
	DISPLAY_INIT_FAIL,
	BLE_INIT_FAIL,
	FLASH_INIT_FAIL,
	IO_EXPANDER_REG_WRITE_FAIL,
	IO_EXPANDER_REG_READ_FAIL,
	PUSH_BTN_INIT_FAIL,
	BATTERY_MONITOR_INIT_FAIL,
	ADS_DRDY_CONFIG_FAIL,
	ECG_DATA_CAPTURE_FAIL,
	PPG_DATA_CAPTURE_FAIL,
	BP_DATA_STORE_TO_FLASH_FAIL,
	ECG_DATA_STORE_TO_FLASH_FAIL,
	SPO2_DATA_STORE_TO_FLASH_FAIL,
	LEAD12_ECG_DATA_STORE_TO_FLASH_FAIL,
	ECG_LEAD12_INIT_FAIL,
}ERROR_CODES_t;


void Catch_RunTime_Error(ERROR_CODES_t Error_code);



#endif
